# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      #- run: npm update

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run ionic:build --prod

      - run: npm run ionic:uglifyjs

      # Run tests? :trollface:

      - add_ssh_keys:
          fingerprints:
            - "e4:aa:d2:fe:95:82:87:a2:78:e0:59:17:d4:fd:d1:41"

      # - deploy:
      #     command: scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r www/ wallet-server@wallet-client.euro2.ee:/opt/wallet-client-webbuild/

      - run: npm run ionic cordova build android --prod --release
      - run: export APK_PATH=./platforms/android/app/build/outputs/apk/release/
      - run: ls -la $APK_PATH
      - run: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./android-release.keystore $APK_PATH/app-release-unsigned.apk beta_app
      - run: $ANDROID_HOME/build-tools/26.0.3/zipalign -v 4 $APK_PATH/app-release-unsigned.apk $APK_PATH/app-release-signed-aligned.apk
